import Head from 'next/head'
import Header from '../components/Header'
import HomeCard from '../components/HomeCard'
import HomeSecondSection from '../components/HomeSecondSection'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <div className="px-4 sm:px-14 md:px-20">
      <Head>
        <title>CatWiki</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </Head>

      <div>
        <Header />

        <HomeCard />

        <HomeSecondSection />

        <Footer />
      </div>


    </div>
  )
}
